spring.application.name=bibflip-gateway

server.port=${SERVER_PORT:8090}


eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka/}

eureka.instance.instance-id=${spring.application.name}:${server.port}


## Gateway Routes Configuration
spring.cloud.gateway.routes[0].id=bibflip-iam-service
spring.cloud.gateway.routes[0].uri=lb://bibflip-iam-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/roles/**,/api/v1/users/**,/api/v1/authentication/**,/api/v1/password-recovery/**

spring.cloud.gateway.routes[1].id=bibflip-booking-service
spring.cloud.gateway.routes[1].uri=lb://bibflip-booking-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/bookings/**,/api/v1/cubicles/**

spring.cloud.gateway.routes[2].id=bibflip-branching-service
spring.cloud.gateway.routes[2].uri=lb://bibflip-branching-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/headquarters/**


## CORS Configuration
#spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
#
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns[0]=http://localhost:5173
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns[1]=http://127.0.0.1:5173
#
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[0]=GET
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[1]=POST
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[2]=PUT
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[3]=PATCH
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[4]=DELETE
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[5]=OPTIONS
#
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers[0]=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].exposed-headers[0]=Authorization
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
#spring.cloud.gateway.globalcors.cors-configurations.[/**].max-age=3600

##Logs
logging.level.root=info
logging.level.org.springframework.cloud.gateway=trace
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=info

## JWT Secret Key for Token Signing Credentials
authorization.jwt.secret = ${JWT_SECRET:H7h1N5nDyb+JgV6vTxMJ0hO7LuZBeL9kFq5eVjz8kzM=}

##CONFIG DE PRUEBA
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true