spring.application.name=bibflip-gateway

server.port=8090


eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka/}

eureka.instance.instance-id=${spring.application.name}:${server.port}


## Gateway Routes Configuration
spring.cloud.gateway.routes[0].id=bibflip-iam-service
spring.cloud.gateway.routes[0].uri=lb://bibflip-iam-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/roles/**,/api/v1/users/**,/api/v1/authentication/**,/api/v1/password-recovery/**

spring.cloud.gateway.routes[1].id=bibflip-booking-service
spring.cloud.gateway.routes[1].uri=lb://bibflip-booking-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/bookings/**,/api/v1/cubicles/**

spring.cloud.gateway.routes[2].id=bibflip-branching-service
spring.cloud.gateway.routes[2].uri=lb://bibflip-branching-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/headquarters/**


## CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/].allowedOrigins[0]=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
spring.cloud.gateway.globalcors.cors-configurations.[/].allowedMethods[0]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/].allowedMethods[1]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/].allowedHeaders[0]=*
spring.cloud.gateway.globalcors.cors-configurations.[/].allowCredentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/].maxAge=3600

##Logs
logging.level.root=info
logging.level.org.springframework.cloud.gateway=trace
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=info

## JWT Secret Key for Token Signing Credentials
authorization.jwt.secret = WriteHereYourSecretStringForTokenSigningCredentials

##CONFIG DE PRUEBA
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true